version: 2

project_name: glance

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/glance
    binary: glance
    ldflags:
      - -s -w
      - -X github.com/midhun-mohan/glance/internal/config.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
